### ISSUE TITLE
How to access data from IRI Data Library?

### ISSUE THREAD

**Issue by RichardSeager** [ocp-cmdg/ingrid2python#12]
So here is my problem now ... having made a figure of precipitation for a region from the CCM3 ensemble mean I want to compare it it the observed precipitation.  The model data was on kage but the observed data (from CRU) is on iridl.ldeo 
Attempting the same url = and xr.open_dataset(url) for the iridl dataset as for the kage one does not find the data so I suspect something more is needed.

**Comment by naomi-henderson** [comment]
It should work the same way from iridl.  Navigate to the data you want to get, click on 'Data Files` tab and then copy the OPeNDAP url (ends with /dods). Note that some of the CRU data is password protected and we won't be able to get it this way.

**Comment by naomi-henderson** [comment]
@RichardSeager , perhaps you could use the CPC Global daily precip instead?  See the 'Advanced Example' called 'Create Dataset from Multiple Netcdf Files' for how to see this data

**Comment by RichardSeager** [comment]
@naomi-henderson worked for GPCC - maybe problem was password protection for CRU.  On to trying to plot two field together!

**Comment by naomi-henderson** [comment]
GPCC has other issues, see
