### ISSUE TITLE
why is this with GPCC not working?

### ISSUE THREAD

**Issue by RichardSeager** [ocp-cmdg/ingrid2python#14]
I am trying to access precip data from GPCC but it seems to end up as Nan and does not plot.  Here I have cut and pasted the code - not sure how else to show what I tried to do.

url = 'http://iridl.ldeo.columbia.edu/SOURCES/.WCRP/.GCOS/.GPCC/.FDP/.version2020/.1p0/.precip/dods '

dsGPCC = xr.open_dataset(url,decode_times=False)

ds1G = dsGPCC.precip.sel(Y=slice(25,40), X=slice(240,265))

dsmeanG = (ds1G.mean(['Y','X']))

by which time it already seems Nan 

Also I am wondering if the later effort to get the time grid right worked:

dsmeanG['T'] =  pd.date_range('01/01/1891', periods=len(dsmeanG['T']), freq='MS')

also how do I see the start and end time of the data set in the Jupyter notebook?  I got that info from Ingrid.

**Comment by naomi-henderson** [comment]
The 'X' grid is  -180  to 180 , so when you select an X slice, you get no data.  If you look at ds1G by typing
print(ds1G) (or letting ds1G be the last line in a cell) you will see that there are 0 X points.

There is a 'Troubleshooting' example for how to change to a 0 to 360 grid, but here is a way to do it using modulo arithmetic:

```
dsGPCC.coords['lon'] = np.mod(dsGPCC['lon'], 360)
dsGPCC = dsGPCC.reindex({ 'lon' : np.sort(dsGPCC['lon'])})
```

As for the T grid, yes, the best way to see the first date is by looking at the original data on ingrid.  It looks like you have done it correctly.  To see your new time grid you could type on the last line of a cell:

```
dsmeanG['T']
```
Normally we could type `dsmeanG.T`, but `.T` also means transpose, so might not give the right answer.

**Comment by naomi-henderson** [comment]
oops, of course `X=slice(-120,-95)` would have worked, also, with no `re.index` !

**Comment by RichardSeager** [comment]
@naomi-henderson  the reindex step returned an error of 'np' is not defined.  I'll use the -120 -90 way.

**Comment by naomi-henderson** [comment]
Ah, you would need to `import numpy as np` first

**Comment by RichardSeager** [comment]
still comes back with nan but I'll check it out further

**Comment by naomi-henderson** [comment]
Well, it is a very odd dataset. Even on IRIDL It seems to have constant values for all months of each year.

**Comment by RichardSeager** [comment]
good idea - I will first get an acceptable time series from some precip data set in Ingrid and then try again with Python ... see Ingrid really is indispensable after all!

**Comment by RichardSeager** [comment]
@naomi-henderson  tried a GPCC version that gives me a nice figure in Ingrid but still reports nan for Jupyter.  Giving up and going to work on the paper instead.  We can look at the data plot again next week.  Have a good weekend.

**Comment by haiboliucu** [comment]
Looks like the problem is on IRIDL. I saved the data.nc from IRIDL and loaded the data.nc in python and it works fine.
If I load the data directly from IRIDL dods, it gives all nan.

**Comment by naomi-henderson** [comment]
I opened a new issue to deal with the IRIDL/dods problem [Issue 15](https://github.com/ocp-cmdg/ingrid2python/issues/15#issue-953804934) separately
