### ISSUE TITLE
convert daily to monthly

### ISSUE THREAD

**Issue by naomi-henderson** [ocp-cmdg/ingrid2python#6]
this would be a quick and easy example to add - someone's first pull request?

**Comment by naomi-henderson** [comment]
@haiboliucu , I just figured out how to center the time grid on the middle of the interval with resample! For this example, we can use:

```
tas_monthly = tas.resample(time='1M',label='left',loffset='15D').mean()
```

**Comment by naomi-henderson** [comment]
I guess I find it confusing that you call the whole dataset `tas`, which is also the variable name.  So when we actually want to plot the data, we must use `tas.tas.plot()`

**Comment by haiboliucu** [comment]
Great it works just as we wanted. I changed dataset as ds as supposed.

**Comment by naomi-henderson** [comment]
great, looks good
