### ISSUE TITLE
Testing a Publications page

### ISSUE THREAD

**Issue by naomi-henderson** [ocp-cmdg/ingrid2python#8]
@RichardSeager - check this page:
[OCP publications](https://ocp-cmdg.github.io/publications/pages/pubs.html)

**Comment by RichardSeager** [comment]
wow!

Richard Seager
Palisades Geophysical Institute/Lamont Research Professor
Lamont Doherty Earth Observatory of Columbia University
61 Route 9W, Palisades, NY 10964
***@***.***
Tel: 845-365-8743
“Who wants it all a bed of roses anyway?”, Lal Waterson, Memories.

**Comment by RichardSeager** [comment]
@naomi-henderson Wow!
