### ISSUE TITLE
How do we do a time box average - the equivalent of in Ingrid T 3 boxAverage or T 12 boxAverage ?

### ISSUE THREAD

**Issue by RichardSeager** [ocp-cmdg/ingrid2python#9]
How do I turn a monthly time series into a time series of annual means?  
I could use:

def is_djf(month):                     # define a function to select the desired months
    return (month >= 12) | (month <= 2)

adjusted for all 12 months but is there a simpler way?

**Comment by naomi-henderson** [comment]
Check out the `Grid Coarsening` item in the `Basic Example` page.  Perhaps it needs a new name?

A more standard method would be (but you might not like the position of the new grid)

```
ds.resample(time='Y').mean()
```

**Comment by RichardSeager** [comment]
Thanks.   Gives the same result as my long method ... maybe call Grid Coarsening by Box Averaging?

**Comment by naomi-henderson** [comment]
Okay, I changed the name - closing the issue now
